blueprint:
  name: Калибровка термоголовки TRV-M2Z на основе внешнего датчика температуры (улучшенная версия)
  description: Автоматическая калибровка температуры термоголовки TRV-M2Z на основе показаний внешнего датчика температуры с учетом режима работы.
  domain: automation
  input:
    external_temp:
      name: Выберите внешний датчик температуры
      description: Список внешних датчиков температуры используемых как источник показаний температуры.
      selector:
        entity:
          domain:
            - sensor
          device_class:
            - temperature
          multiple: false
    climate_names:
      name: Выберите термоголовку TRV-M2Z
      description: Список термоголовок.
      selector:
        entity:
          domain:
            - climate
          multiple: true
  source_url: https://github.com/bibibi-Matrix/calib_trv_external_temp/blob/main/blueprints/calib_trv_external_temp.yaml

alias: Калибровка термоголовки TRV-M2Z (улучшенная)
description: ''
variables:
  climate_names: !input climate_names
  external_temperature: !input external_temp

trigger:
  - platform: state
    entity_id: !input external_temp
    for:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - platform: state
    entity_id: !input climate_names
    for:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0

condition:
  condition: and
  conditions:
    - condition: template
      value_template: '{{ states(external_temperature) != ''unavailable'' }}'
    - condition: template
      value_template: '{{ states(external_temperature) != ''unknown'' }}'

action:
  - repeat:
      for_each: "{{ climate_names }}"
      sequence:
        - variables:
            climate_name: "{{ repeat.item }}"
            device_calib: "number.{{ climate_name.removeprefix('climate.') }}_local_temperature_calibration"
            external_temp: "{{ states(external_temperature) | float }}"
            local_temp: "{{ state_attr(climate_name, 'current_temperature') | float }}"
            target_temp: "{{ state_attr(climate_name, 'temperature') | float }}"
            hvac_action: "{{ state_attr(climate_name, 'hvac_action') }}"
            hvac_mode: "{{ states(climate_name) }}"
            actual_calib: "{{ states(device_calib) | float(0) }}"
            
            # Определяем разницу температур
            temp_diff: "{{ (external_temp | float - local_temp | float) }}"
            
            # Температурная точность (обычно 0.5°C для большинства TRV)
            temp_accuracy: 0.5
            
            # Логика калибровки в зависимости от режима работы
            target_calib_raw: >
              {% set diff = temp_diff | float %}
              {% if hvac_mode == 'off' %}
                {{ diff }}
              {% elif hvac_action == 'heating' %}
                {{ diff - temp_accuracy }}
              {% elif hvac_action == 'idle' %}
                {{ diff + temp_accuracy }}
              {% else %}
                {{ diff }}
              {% endif %}
            
            # Преобразуем в число и округляем до ближайшего 0.5
            target_calib_numeric: >
              {% set raw_val = target_calib_raw | float %}
              {{ (raw_val / 0.5) | round * 0.5 }}
            
            # Ограничиваем диапазон калибровки (-9 до +9)
            target_calib_final: >
              {% set val = target_calib_numeric | float %}
              {{ [9, val] | min | round(1) }}
            target_calib_final_clamped: >
              {% set val = target_calib_final | float %}
              {{ [-9, val] | max | round(1) }}
            
            # Проверяем необходимость изменения (с учетом точности 0.1)
            calib_needed: >
              {% set current = actual_calib | float | round(1) %}
              {% set target = target_calib_final_clamped | float | round(1) %}
              {{ current != target }}

        - alias: "Проверка необходимости калибровки"
          condition: template
          value_template: "{{ calib_needed }}"

        - service: number.set_value
          target:
            entity_id: "{{ device_calib }}"
          data:
            value: "{{ target_calib_final_clamped }}"

  - delay: 5

mode: single
max_exceeded: silent
