blueprint:
  name: Калибровка термоголовки TRV-M2Z на основе внешнего датчика с логикой нагрева
  description: |
    Автоматическая калибровка температуры термоголовки TRV-M2Z на основе внешнего датчика температуры,
    с учётом текущего режима работы (нагрев/остывание).
  domain: automation
  input:
    external_temp:
      name: Выберите внешний датчик температуры
      selector:
        entity:
          domain: sensor
          device_class: temperature
    climate_names:
      name: Термоголовки для калибровки
      selector:
        entity:
          domain: climate
          multiple: true
    offset_factor:
      name: Коэффициент коррекции
      description: >
        От 0 до 2. Чем выше — тем сильнее влияние разницы между целевой и внешней температурой.
      default: 1
      selector:
        number:
          min: 0
          max: 2
          step: 0.1

alias: Калибровка термоголовки TRV-M2Z V3
description: ''
mode: single
max_exceeded: silent

variables:
  climate_names: !input climate_names
  external_temperature: !input external_temp
  offset_factor: !input offset_factor

trigger:
  - platform: state
    entity_id: !input external_temp
    for:
      seconds: 15
  - platform: state
    entity_id: !input climate_names
    attribute: hvac_action
    for:
      seconds: 15

condition:
  condition: and
  conditions:
    - condition: template
      value_template: "{{ states(external_temperature) not in ['unavailable', 'unknown'] }}"
    - condition: template
      value_template: "{{ states(external_temperature) | float(-999) != -999 }}"

action:
  - repeat:
      for_each: "{{ climate_names }}"
      sequence:
        - variables:
            climate_name: "{{ repeat.item }}"
            device_calib: "number.{{ climate_name.removeprefix('climate.') }}_local_temperature_calibration"
            external_temp: "{{ states(external_temperature) | float() }}"
            target_temp: "{{ state_attr(climate_name, 'temperature') | float() }}"
            hvac_action: "{{ state_attr(climate_name, 'hvac_action') }}"
            actual_calib: "{{ states(device_calib) | float(0) }}"

            # Определение коррекции в зависимости от режима
            diff_target_external: "{{ target_temp - external_temp }}"

            raw_correction: >
              {% if hvac_action == 'heating' %}
                {{ diff_target_external * offset_factor }}
              {% elif hvac_action in ['idle', 'off'] %}
                {{ diff_target_external * offset_factor * -0.5 }}
              {% else %}
                0
              {% endif %}

            target_calib: "{{ raw_correction }}"
            target_calib_rounded: "{{ ((target_calib * 2) | round) / 2 }}"
            target_calib_clamped: "{{ [ [target_calib_rounded, 9] | min, -9] | max }}"

        - condition: template
          value_template: "{{ actual_calib != target_calib_clamped }}"

        - service: number.set_value
          target:
            entity_id: "{{ device_calib }}"
          data:
            value: "{{ target_calib_clamped }}"

  - delay: 5
