blueprint:
  name: Калибровка термоголовки TRV-M2Z на основе внешнего датчика температуры V3
  description: |
    Автоматическая калибровка термоголовки TRV-M2Z с учётом режима работы и точности измерения.
  domain: automation
  input:
    external_temp:
      name: Выберите внешний датчик температуры
      selector:
        entity:
          domain: sensor
          device_class: temperature
          multiple: false
    climate_names:
      name: Выберите термоголовки TRV-M2Z
      selector:
        entity:
          domain: climate
          multiple: true
    temp_accuracy:
      name: Точность измерения температуры
      description: Используется для расчёта границ (± точность от целевой температуры).
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 2
          step: 0.1
  source_url: https://github.com/bibibi-Matrix/calib_trv_external_temp/blob/main/blueprints/calib_test.yaml

alias: Калибровка термоголовки TRV-M2Z V3
description: ''
mode: single
max_exceeded: silent

variables:
  climate_names: !input climate_names
  external_temperature: !input external_temp
  temp_accuracy: !input temp_accuracy

trigger:
  - platform: state
    entity_id: !input external_temp
    for:
      seconds: 15
  - platform: state
    entity_id: !input climate_names
    for:
      seconds: 15

condition:
  condition: and
  conditions:
    - condition: template
      value_template: "{{ states(external_temperature) not in ['unavailable', 'unknown'] }}"
    - condition: template
      value_template: "{{ states(external_temperature) | float(-999) != -999 }}"

action:
  - repeat:
      for_each: "{{ climate_names }}"
      sequence:
        - variables:
            climate_name: "{{ repeat.item }}"
            device_calib: "number.{{ climate_name.removeprefix('climate.') }}_local_temperature_calibration"
            hvac_action: "{{ state_attr(climate_name, 'hvac_action') }}"
            external_temp: "{{ states(external_temperature) | float() }}"
            local_temp: "{{ state_attr(climate_name, 'current_temperature') | float() }}"
            target_temp: "{{ state_attr(climate_name, 'temperature') | float() }}"
            actual_calib: "{{ states(device_calib) | float(0) }}"

            lower_bound: "{{ target_temp - temp_accuracy }}"
            upper_bound: "{{ target_temp + temp_accuracy }}"

            # Выбор целевой температуры в зависимости от режима
            target_for_calibration: >
              {% if hvac_action == 'off' %}
                {{ external_temp }}
              {% elif hvac_action == 'idle' %}
                {{ lower_bound }}
              {% elif hvac_action == 'heating' %}
                {{ upper_bound }}
              {% else %}
                {{ external_temp }}
              {% endif %}

            # Расчёт новой калибровки
            new_calib_raw: "{{ target_for_calibration - (local_temp - actual_calib) }}"
            new_calib_rounded: "{{ ((new_calib_raw * 2) | round) / 2 }}"
            new_calib_clamped: "{{ [ [new_calib_rounded, 9] | min, -9] | max }}"

        - condition: template
          value_template: "{{ actual_calib != new_calib_clamped }}"

        - service: number.set_value
          target:
            entity_id: "{{ device_calib }}"
          data:
            value: "{{ new_calib_clamped }}"

  - delay: 5
