blueprint:
  name: Калибровка термоголовки TRV-M2Z на основе внешнего датчика температуры V4
  description: |
    Автоматическая калибровка температуры термоголовки TRV-M2Z на основе показаний внешнего датчика температуры с учетом режима работы.
  domain: automation
  input:
    external_temp:
      name: Выберите внешний датчик температуры
      description: Список внешних датчиков температуры, используемых как источник показаний температуры.
      selector:
        entity:
          domain:
            - sensor
          device_class:
            - temperature
          multiple: false
    climate_names:
      name: Выберите термоголовку TRV-M2Z
      description: Список термоголовок.
      selector:
        entity:
          domain:
            - climate
          multiple: true
  source_url: https://github.com/bibibi-Matrix/calib_trv_external_temp/blob/main/blueprints/calib_test.yaml

alias: Калибровка термоголовки TRV-M2Z V4
description: ''
mode: single
max_exceeded: silent

variables:
  climate_names: !input climate_names
  external_temperature: !input external_temp

trigger:
  - platform: state
    entity_id: !input external_temp
    for:
      hours: 0
      minutes: 0
      seconds: 15
  - platform: state
    entity_id: !input climate_names
    attribute: hvac_action
    for:
      hours: 0
      minutes: 0
      seconds: 15

condition:
  condition: and
  conditions:
    - condition: template
      value_template: "{{ states(external_temperature) not in ['unavailable', 'unknown'] }}"
    - condition: template
      value_template: "{{ states(external_temperature) | float(-999) != -999 }}"

action:
  - repeat:
      for_each: "{{ climate_names }}"
      sequence:
        - variables:
            climate_name: "{{ repeat.item }}"
            device_calib: "number.{{ climate_name.removeprefix('climate.') }}_local_temperature_calibration"
            external_temp: "{{ states(external_temperature) | float() }}"
            local_temp: "{{ state_attr(climate_name, 'current_temperature') | float() }}"
            target_temp: "{{ state_attr(climate_name, 'temperature') | float() }}"
            hvac_action: "{{ state_attr(climate_name, 'hvac_action') }}"
            actual_calib: "{{ states(device_calib) | float(0) }}"

            # Границы
            lower_bound: "{{ target_temp - 0.5 }}"
            upper_bound: "{{ target_temp }}"

            # Определение желаемой внешней температуры для калибровки
            desired_external_temp: >-
              {% if hvac_action == 'heating' %}
                {{ lower_bound }}
              {% elif hvac_action == 'idle' %}
                {{ upper_bound }}
              {% else %}
                {{ external_temp }}
              {% endif %}

            # Расчёт новой калибровки: local_temp + (desired_external_temp - external_temp)
            new_calib_raw: "{{ actual_calib + (desired_external_temp - external_temp) }}"
            new_calib_rounded: "{{ ((new_calib_raw * 2) | round) / 2 }}"
            new_calib_clamped: "{{ [ [new_calib_rounded, 9] | min, -9] | max }}"

        - condition: template
          value_template: "{{ actual_calib != new_calib_clamped }}"

        - service: number.set_value
          target:
            entity_id: "{{ device_calib }}"
          data:
            value: "{{ new_calib_clamped }}"

  - delay: 5
