blueprint:
  name: Калибровка термоголовки TRV-M2Z на основе внешнего датчика температуры V3
  description: |
    Автоматическая калибровка температуры термоголовки TRV-M2Z на основе показаний внешнего датчика температуры.
  domain: automation
  input:
    external_temp:
      name: Выберите внешний датчик температуры
      description: Список внешних датчиков температуры, используемых как источник показаний температуры.
      selector:
        entity:
          domain:
            - sensor
          device_class:
            - temperature
          multiple: false
    climate_names:
      name: Выберите термоголовку TRV-M2Z
      description: Список термоголовок.
      selector:
        entity:
          domain:
            - climate
          multiple: true
    offset_factor:
      name: Коэффициент коррекции
      description: >
        Добавляет взвешенную разницу между текущей и целевой температурой.
        Формула: коэффициент * (фактическая температура - целевая температура).

        При следующих значениях:
        0   — коррекция не применяется;
        0.5 — частичная компенсация;
        1   — полная компенсация;
        >1  — усиленная коррекция (максимум 2).
      default: 0
      selector:
        number:
          min: 0
          max: 2
          step: 0.1
  source_url: https://github.com/bibibi-Matrix/calib_trv_external_temp/blob/main/blueprints/calib_test.yaml

alias: Калибровка термоголовки TRV-M2Z V3
description: ''
mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input external_temp
    for:
      hours: 0
      minutes: 0
      seconds: 15
  - platform: state
    entity_id: !input climate_names
    attribute: current_temperature
    for:
      hours: 0
      minutes: 0
      seconds: 15

condition:
  condition: and
  conditions:
    - condition: template
      value_template: "{{ states(external_temperature) not in ['unavailable', 'unknown'] }}"
    - condition: template
      value_template: "{{ states(external_temperature) | float(-999) != -999 }}"

action:
  - repeat:
      for_each: >-
        {% set climates = climate_names if climate_names is list else [climate_names] %}
        {{ climates }}
      sequence:
        - variables:
            climate_name: "{{ repeat.item }}"
            device_calib: "number.{{ climate_name.removeprefix('climate.') }}_local_temperature_calibration"
            external_temp: "{{ states(external_temperature) | float() }}"
            local_temp: "{{ state_attr(climate_name, 'current_temperature') | float() }}"
            target_temp: "{{ state_attr(climate_name, 'temperature') | float() }}"
            actual_calib: "{{ states(device_calib) | float(0) }}"
            temp_diff: "{{ external_temp - target_temp }}"
            calibration_offset: "{{ temp_diff * offset_factor }}"
            target_calib: "{{ external_temp - (local_temp - actual_calib) + calibration_offset }}"

            hvac_action: "{{ state_attr(climate_name, 'hvac_action') | default('off') }}"

            # Уточнённое условное округление
            target_calib_rounded: >-
              {% set diff = external_temp - target_temp %}
              {% if hvac_action == 'heat' and diff < 0 and diff > -0.5 %}
                {{ (target_calib // 0.5) * 0.5 }}
              {% elif hvac_action == 'idle' and diff < 0 and diff > -0.5 %}
                {{ -( (-target_calib) // 0.5 ) * 0.5 }}
              {% else %}
                {{ ((target_calib * 2) | round) / 2 }}
              {% endif %}

            target_calib_clamped: "{{ [ [target_calib_rounded, 9] | min, -9] | max }}"

        - condition: template
          value_template: "{{ actual_calib != target_calib_clamped }}"

        - service: number.set_value
          target:
            entity_id: "{{ device_calib }}"
          data:
            value: "{{ target_calib_clamped }}"

  - delay: 5
